version: 2
mergeable:
  - when: pull_request.opened
    name: 'Check for release note'
    validate:
      - do: changeset
        must_include:
            regex: 'help/en/releasenotes/current-draft-note.shtml'
    fail:
      - do: comment
        payload:
          body: > 
            Thanks for the PR. Please consider adding a release note in the help/en/releasenotes/current-draft-note.shtml file.
  - when: pull_request.opened
    name: 'Ensure author assigned'
    validate:
      - do: assignee
        min:
          count: 1 # Should be assigned to somebody; if not, assign author
    fail:
      - do: assign
        assignees: [ '@author' ] 
      - do: checks
        status: 'success' # Supply the default actions, as if this passed.
        payload:
          title: 'Mergeable Run have been Completed!'
          summary: "All the validators have returned 'pass'! \n Here are some stats of the run: \n {{validationCount}} validations were ran"
       