version: '{build}'
clone_depth: 50
install:
  - choco install ant --limit-output
  - echo JAVA_HOME %JAVA_HOME%
  - echo PATH %PATH%
#  - SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0_66
#  - echo PATH %PATH%
#  - echo JAVA_HOME %JAVA_HOME%
  - echo ANT_HOME %ANT_HOME%
  - java -version
#  - javac -version
  - ant -version
build: off

test_script:
- ps: >-
    ant appveyor-ci-test

after_test:
- ps: >-    
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\junit-results.xml))

deploy: off
