version: '{build}'
clone_depth: 50
install:
  - SET MAVEN_HOME=C:\tools\apache-maven-3.3.3
  - if not exist %MAVEN_HOME% (
      choco install maven -y --version 3.3.3
    )
  - refreshenv
  - SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - SET PATH=%MAVEN_HOME%\bin;%JAVA_HOME%\bin;%PATH%
  - # echo PATH %PATH%
  - java -version
  - mvn -version
build: off

# note that PowerShell scripts need an empty line between each command
# this is not normal for PowerShell and is likely a side effect of
# AppVeyor's YAML processing
test_script:
- ps: >-
    mvn test -P appveyor --quiet --batch-mode

on_finish:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$env:APPVEYOR_JOB_ID", (Resolve-Path .\junit-results.xml))

deploy: off

cache:
  - C:\tools\apache-maven-3.3.3
  - C:\Users\appveyor\.m2
